### ISSUE TITLE
Use a "source profile" for profiles

### ISSUE THREAD

**Issue by jacobbednarz** [jacobbednarz/cf-vault#30]
It would be handy to have a source profile (such as the ability to create API tokens) which could be shared to other profiles without duplicating the credentials. Right now, if I want a read and write profile, I need to duplicate it and setup two. In practice, the ideal would look like this:

```toml
[profiles]

[profiles.create_single_use_token]
auth_type = "api_token"

[profiles.write_everything]
source_profile = "create_single_use_token"
```
